export __ZLD_PRODUCT_SPEC_H:=
export ZLD_PRODUCT_LINE_USG:=(100)
export ZLD_PRODUCT_LINE_ENTERPRISE_WLAN:=(200)
export ZLD_PRODUCT_LINE_MSBG:=(300)
export ZLD_PRODUCT_LINE_NAME_USG:="ZyWALL"
export ZLD_PRODUCT_LINE_NAME_ENTERPRISE_WLAN:="EnterpriseWLAN"
export ZLDSYSPARM_PRODUCT_LINE:=(200)
export ZLDSYSPARM_PRODUCT_LINE_NAME:="EnterpriseWLAN"
export ZLDSYSPARM_PRODUCT_LINE_ZONE_NAME:="EnterpriseWLAN"
# ZLDCONFIG_GUI_LATEST_FW_NOTIFICATION_SUPPORT is not set
# ZLDCONFIG_CAPWAP_WTP_SUPPORT is not set
export ZLDCONFIG_MULTI_LINGUAL:=1
export ZLDCONFIG_WLAN_PROFILE_ENABLE:=1
# ZLDCONFIG_WLAN_MACFILTER_PROFILE_ENHANCE is not set
export ZLDCONFIG_WLAN_SECURITY_PROFILE_ACCOUNTING:=1
export ZLDCONFIG_WLAN_SECURITY_PROFILE_EAP_AUTH_DEFAULT_EXTERNAL:=1
# ZLDCONFIG_WLAN_RADIO_PROFILE_WDS_SETTING is not set
export ZLDCONFIG_WLAN_4MAC_WDS_SUPPORT:=1
export ZLDCONFIG_WLAN_ENABLE:=1
# ZLDCONFIG_WLAN_SMART_ANTENNA_SUPPORT is not set
export ZLDCONFIG_NO_ZYSH_NF_CT_BYPASS_LOGIN_PORT:=1
export ZLDCONFIG_DAILY_REPORT:=1
export ZLDCONFIG_CAPWAP_DAILY_REPORT:=1
# ZLDCONFIG_CUSTOMIZED_LOGIN_PAGE is not set
export ZLDCONFIG_DISKLOG_MTDOOPS:=1
export ZLDCONFIG_PKI:=1
export ZLDCONFIG_PKI_UNUSED:=1
export ZLDCONFIG_NO_ZYSH_LOG_SEND_SYS_INFO:=1
# ZLDCONFIG_NO_ZYSH_DEBUG_MANUFACTURE is not set
# ZLDCONFIG_NO_ZYSH_CISCO_HTTP is not set
# ZLDCONFIG_NO_ZYSH_CISCO_HTTPS is not set
# ZLDCONFIG_NO_ZYSH_CISCO_SNMP is not set
# ZLDCONFIG_NO_GUI_AUTOMATION is not set
export ZLDCONFIG_NO_ROGUEAP_CONTAINMENT_GUI:=1
export ZLDCONFIG_NO_5G_OBJECTS:=1
export ZLDCONFIG_GUI_DOWN_SIZE:=1
export ZLDCONFIG_WLAN_L2ISOLATION:=1
export ZLDCONFIG_GUEST_SSID_SUPPORT:=1
export ZLDCONFIG_NO_DNS_SERVER:=1
export ZLDCONFIG_HTTPD:=1
export ZLDCONFIG_HTTPD_DOWN_SIZE:=1
# ZLDCONFIG_LIBOL is not set
# ZLDCONFIG_HTTP_REDIRECT is not set
export ZLDCONFIG_PCI_DSS_SUPPORT:=1
export ZLDCONFIG_IPV6:=1
export ZLDCONFIG_IPV6_GLOBAL_SWITCH:=1
export ZLDCONFIG_GPIO_3_COLOR_LED:=1
export ZLDCONFIG_LED_SUPPRESS_MODE_SUPPORT:=1
# ZLDCONFIG_LED_BUTTON_CONTROL is not set
# ZLDCONFIG_LED_SUPPRESS_DEFAULT_ON is not set
export ZLDCONFIG_LED_SOFTWARE_CONTROL:=1
export ZLDCONFIG_LED_LOCATOR_SUPPORT:=1
# ZLDCONFIG_BLE_SUPPORT is not set
export ZLDCONFIG_8021Q_VLAN_ENHANCE_AP:=1
# ZLDCONFIG_SWITCH_SW_VLAN is not set
export ZLDCONFIG_SWITCH_HW_VLAN:=1
# ZLDCONFIG_SWITCH_IPQ807X_VLAN is not set
# ZLDCONFIG_SWITCHPORT_REMAP_DEV is not set
# ZLDCONFIG_WTP_WTP_LOOPGUARD is not set
# ZLDCONFIG_WLAN_MON_MODE_SERVER_SUPPORT is not set
# ZLDCONFIG_WLAN_MON_MODE_CLIENT_SUPPORT is not set
export ZLDCONFIG_WLAN_RAD_AC_SUPPORT:=1
# ZLDCONFIG_WLAN_RAD_WTP_SUPPORT is not set
# ZLDCONFIG_WLAN_FRAME_CAPTURE_SERVER_SUPPORT is not set
# ZLDCONFIG_WLAN_FRAME_CAPTURE_CLIENT_SUPPORT is not set
export ZLDCONFIG_WLAN_APMODE_RAPD_SERVER_SUPPORT:=1
export ZLDCONFIG_WLAN_APMODE_RAPD_CLIENT_SUPPORT:=1
# ZLDCONFIG_WLAN_DCS_AC_SUPPORT is not set
export ZLDCONFIG_WLAN_DCS_WTP_SUPPORT:=1
export ZLDCONFIG_WLAN_DCS_SCHEDULE_SUPPORT:=1
export ZLDCONFIG_WLAN_SSID_SCHEDULE_SUPPORT:=1
# ZLDCONFIG_WLAN_BAND_SELECT_AC_SUPPORT is not set
export ZLDCONFIG_WLAN_BAND_SELECT_WTP_SUPPORT:=1
export ZLDCONFIG_WLAN_RSSI_THRESHOLD:=1
export ZLDCONFIG_WLAN_RSSI_THRESHOLD_SUPPORT_IDLE_CHK:=1
# ZLDCONFIG_WLAN_AUTO_HEALING_AC_SUPPORT is not set
# ZLDCONFIG_WLAN_AUTO_HEALING_WTP_SUPPORT is not set
export ZLDCONFIG_AP_LOAD_BALANCING_SERVER_SUPPORT:=1
export ZLDCONFIG_AP_LOAD_BALANCING_CLIENT_SUPPORT:=1
export ZLDCONFIG_LEGACY_STA_REJECTION:=1
export ZLDCONFIG_SNMP_TRAP:=1
export ZLDCONFIG_WIRELESS_HAL_SUPPORT:=1
export ZLDCONFIG_WLAN_CLIENT_INFO:=1
export ZLDCONFIG_WLAN_AP_PROXY_ARP:=1
export ZLDCONFIG_WLAN_STATION_INFO_COLLECTION:=1
export ZLDCONFIG_WLAN_CSA_INTEROP:=1
export ZLDCONFIG_WLAN_160MHZ_SUPPORT:=1
# ZLDCONFIG_WEBLOGIN_OTP is not set
export ZLDCONFIG_WEBLOGIN_WIZARD:=1
# ZLDCONFIG_USER_EXT_USER_PWLAN_WORKAROUND is not set
# ZLDCONFIG_USER_GUEST_PWLAN_WORKAROUND is not set
# ZLDCONFIG_USER_GROUP_PWLAN_WORKAROUND is not set
# ZLDCONFIG_USER_LOGIN_PWLAN_WORKAROUND is not set
export ZLDCONFIG_AAA_OBJECT_PWLAN_WORKAROUND:=1
# ZLDCONFIG_AAA_OBJECT_AD_PWLAN_WORKAROUND is not set
# ZLDCONFIG_AAA_OBJECT_LDAP_PWLAN_WORKAROUND is not set
export ZLDCONFIG_AAA_FREERADIUS:=1
export ZLDCONFIG_AAA_FREERADIUS_AUTH_SERVER:=1
export ZLDCONFIG_AAA_FREERADIUS_MODIFY:=1
# ZLDCONFIG_AAA_DOMAIN_AUTH is not set
export ZLDCONFIG_FREERADIUS_HOSTAPD_ATTRIBUTE:=1
export ZLDCONFIG_AAA_FREERADIUS_UAM:=1
export ZLDCONFIG_LOGIN_WITHOUT_UAM:=1
export ZLDCONFIG_AAA_MAC_AUTH:=1
export ZLDCONFIG_AAA_MAC_AUTH_ACCOUNTING:=1
# ZLDCONFIG_MAC_AUTH_FALLBACK is not set
export ZLDCONFIG_AAA_INTERNAL_EAP_PROXY:=1
export ZLDCONFIG_AAA_8021X_ACCOUNTING:=1
export ZLDCONFIG_AAA_DYNAMIC_AUTHORIZATION_SERVER:=1
export ZLDCONFIG_AAA_RADIUS_ACCT:=1
export ZLDCONFIG_RADIUS_ATTR_SUPPORT:=1
export ZLDCONFIG_AAA_HOST_FQDN_SUPPORT:=1
# ZLDCONFIG_AAA_FREE_ACCESS_SUPPORT is not set
export ZLDCONFIG_PWLAN_SYSTEM_WORKAROUND_SUPPORT:=1
export ZLDCONFIG_TUNNEL_DTLS_SUPPORT:=1
# ZLDCONFIG_DATA_FORWARD_CLIENT_SUPPORT is not set
export ZLDCONFIG_WTP_IMAGE_UPGRADE_MUTI_METHODS:=1
# ZLDCONFIG_DATA_FORWARD_SERVER_SUPPORT is not set
# ZLDCONFIG_CAPWAP_WTP_WTP_LOGS_SUPPORT is not set
# ZLDCONFIG_CAPWAP_AC_WTP_LOGS_SUPPORT is not set
export ZLDCONFIG_CAPWAP_WTP_STATUS_NOTIFY_SUPPORT:=1
# ZLDCONFIG_CAPWAP_LOCAL_WLAN_SUPPORT is not set
export ZLDCONFIG_ZYKIT:=1
export ZLDCONFIG_MULTIPLE_PRODUCT:=1
export ZLDCONFIG_ENTERPRISE_WLAN_HYBRID:=1
export ZLDCONFIG_DEBUG_ACCOUNT_ENHANCEMENT_V2:=1
export ZLDCONFIG_SNMPV3_SUPPORT:=1
# ZLDCONFIG_SNMPV2_SUPPORT is not set
export ZLDCONFIG_SNMP_DOWN_SIZE:=1
export ZLDCONFIG_WLAN_SECURITY_PROFILE_EAP_AUTH_DEFAULT_EXTERNAL:=1
export ZLDCONFIG_FORCE_AUTH_PWLAN_WORKAROUND:=1
# ZLDCONFIG_ADDRESS_OBJECT_PWLAN_WORKAROUND is not set
# ZLDCONFIG_SERVICE_OBJECT_PWLAN_WORKAROUND is not set
# ZLDCONFIG_SCHEDULE_OBJECT_PWLAN_WORKAROUND is not set
export ZLDCONFIG_NO_VD_PWLAN_WORKAROUND:=1
# ZLDCONFIG_WTP_IMG_POST_ACTION is not set
# ZLDCONFIG_SINGLE_FW_UPDATE is not set
export ZLDCONFIG_FIRMWARE_UNIFY:=1
export ZLDCONFIG_STANDALONE_AC_DISCOVERY:=1
# ZLDCONFIG_KEEP_SELF_IMG_TO_WTP_IMG is not set
# ZLDCONFIG_AUTO_WTP_IMG_DOWNLOAD is not set
# ZLDCONFIG_GUI_LOGIN_USERS_PWLAN_WORKAROUND is not set
export ZLDCONFIG_AP_MIX_LAN:=1
export ZLDCONFIG_BRIDGE_USERDEFINE_NAME:=1
export ZLDCONFIG_GE_INTERFACE_HIDDEN:=1
export ZLDCONFIG_VLAN_INTERFACE_HIDDEN:=1
export ZLDCONFIG_PROWLAN_IPC:=1
export ZLDCONFIG_PROWLAN_RESD:=1
# ZLDCONFIG_IEEE_8023AZ is not set
export ZLDCONFIG_FORCE_KSOFTIRQD:=1
export ZLDCONFIG_DHCP_CLIENT_ENABLE_ARP_CHECK:=1
export ZLDCONFIG_RTLS_SUPPORT:=1
export ZLDCONFIG_RTLS_EKAHAU_SUPPORT:=1
export ZLDCONFIG_ZYSH_WLAN_OP_DEBUG:=1
export ZLDCONFIG_NO_WEB_CONSOLE:=1
# ZLDCONFIG_NO_HTB_DIRECT_QUEUE is not set
export ZLDCONFIG_BMM:=1
export ZLDCONFIG_BMM_MTD:=1
export ZLDCONFIG_SCAN_AGENT_WTP_SUPPORT:=1
export ZLDCONFIG_SMART_MESH_SUPPORT:=1
# ZLDCONFIG_ZYMESH_SUPPORT is not set
export ZLDCONFIG_WIRELESS_BRIDGE_SUPPORT:=1
export ZLDCONFIG_WLAN_HY_FWD:=1
# ZLDCONFIG_COREDUMP_IN_RAM is not set
# ZLDCONFIG_COREDUMP_IN_DB is not set
# ZLDSYSPARM_COREDUMP_FILE_QUOTA is not set
export ZLDCONFIG_WTP_GDB_SUPPORT:=1
export ZLDCONFIG_GUI_CLOUD_WEB_HELP:=1
# ZLDCONFIG_COUNTRY_CODE_AC is not set
export ZLDCONFIG_COUNTRY_CODE_AP:=1
# ZLDCONFIG_TX_POWER_DEBUG_AC is not set
export ZLDCONFIG_TX_POWER_DEBUG_AP:=1
export ZLDCONFIG_DOT11W_SUPPORT:=1
export ZLDCONFIG_WLAN_ABS_POWER_SUPPORT:=1
export ZLDCONFIG_STA_INFO_CLEAN_WAR:=1
export ZLDCONFIG_STA_INFO_ENHANCEMENT:=1
export ZLDCONFIG_DOT11R_SUPPORT:=1
export ZLDCONFIG_WLAN_RATELIMIT_SUPPORT:=1
# ZLDCONFIG_DHCP_OPTION_82_SUPPORT is not set
export ZLDCONFIG_OPENSSL_111_SUPPORT:=1
export ZLDCONFIG_DB_SUPPORT:=1
export ZLDCONFIG_RRM_SUPPORT:=1
export ZLDCONFIG_WIRELESS_HAL_RRM_SUPPORT:=1
export ZLDCONFIG_DFS_CHANNEL_SWITCH_ENHANCE:=1
export ZLDCONFIG_DFS_CHANNEL_SELECT_ENHANCE:=1
export ZLDCONFIG_DFS_CHANNEL_BLOCK_FOREVER:=1
export ZLDCONFIG_DFS_CHANNEL_BLOCK_WTP_SUPPORT:=1
export ZLDCONFIG_DOT11K_SUPPORT:=1
export ZLDCONFIG_ROAMING_GROUP:=1
export ZLDCONFIG_NEIGHBOR_COLLETOR:=1
export ZLDCONFIG_INITIAL_SETUP_SSID:=1
# ZLDCONFIG_FALLBACK_SSID_SUPPORT is not set
export ZLDCONFIG_WLAN_WPA3_SUPPORT:=1
export ZLDCONFIG_WLAN_THERMAL_CONTROL:=1
# ZLDCONFIG_MU_DISABLE_WORKAROUND is not set
export ZLDCONFIG_WIRELESS_HEALTH_SUPPORT:=1
export ZLDCONFIG_CHANNEL_INFO:=1
# ZLDCONFIG_WLAN_DPPSK_SUPPORT is not set
export ZLDCONFIG_IGNORE_COUNTRY_IE_SUPPORT:=1
export ZLDCONFIG_WLAN_RATE_CONTROL_SUPPORT:=1
# ZLDCONFIG_FLASH_DOWN_SIZE is not set
export ZLDCONFIG_ZYLOG_DOWN_SIZE:=1
export ZLDCONFIG_KISMET_DOWN_SIZE:=1
export ZLDCONFIG_IPROUTE2_DOWN_SIZE:=1
export ZLDCONFIG_LIBPNG_DOWN_SIZE:=1
export ZLDCONFIG_EXPAT_DOWN_SIZE:=1
export ZLDCONFIG_SYSLOG_NG_DOWN_SIZE:=1
export ZLDCONFIG_HOSTAPD_DOWN_SIZE:=1
export ZLDCONFIG_PKI_DOWN_SIZE:=1
export ZLDCONFIG_GD_DOWN_SIZE:=1
export ZLDCONFIG_NTP_DOWN_SIZE:=1
export ZLDCONFIG_UAM_DOWN_SIZE:=1
export ZLDCONFIG_LIBXML_DOWN_SIZE:=1
export ZLDCONFIG_GMP_DOWN_SIZE:=1
export ZLDCONFIG_INFO_TRANSFER_WTP_SUPPORT:=1
export ZLDCONFIG_MULTIBOOT_SUPPORT:=1
export ZLDCONFIG_AP_RECOVERY_SUPPORT:=1
export ZLDCONFIG_HARDWARE_REBOOT_SUPPORT:=1
export ZLDCONFIG_ZDP:=1
export ZLDCONFIG_LLDP:=1
export ZLDCONFIG_LLDP_SUPPORT_RCD:=1
# ZLDCONFIG_LLDP_POWER_VIA_MDI is not set
# ZLDCONFIG_POWER_SOURCE_CHANGE_DETECT is not set
# ZLDCONFIG_OVERRIDE_FULL_POWER_SUPPORT is not set
export ZLDCONFIG_ZWO_WTP_SUPPORT:=1
# ZLDCONFIG_ZWO_AC_SUPPORT is not set
export ZLDCONFIG_DUMP_CONSOLE_MSG_TO_SSH_CLIENT:=1
# ZLDCONFIG_WEB_PORTAL_REDIRECT_FROM_AP is not set
export ZLDCONFIG_PLATFORM_MIPSEL_MEDIATEK_MT7621:=1
export ZLDCONFIG_PLATFORM_MIPSEL_MEDIATEK_MT7621_FIXME:=1
export BOOT_MODULE_CHECKSUM_SUPPORT:=1
export ZLDCONFIG_BM_HTP_DRAM_DISABLE:=1
export ZLDCONFIG_BUSYBOX:=1
export ZLDCONFIG_LIBTIRPC:=1
export ZLDCONFIG_BOOTUP_NOLOOP:=1
# ZLDCONFIG_MFGCONFIG_SUPPORT is not set
export ZLDCONFIG_UBIFS_SUPPORT:=1
export ZLDCONFIG_NAND_SUPPORT:=1
export ZLDCONFIG_BOARD_NWA50AX:=1
export ZLDSYSPARM_PLATFORM_NAME:="mt7621"
export ZLDSYSPARM_PRODUCT_NAME:="nwa50ax"
export ZLDSYSPARM_PRODUCT_NAME1:="NWA50AX"
export ZLDSYSPARM_PRODUCT_LINE_FAMILY_NAME:="NWA50AX"
export ZLDSYSPARM_PRODUCT_CNM:="WAX"
export ZLDSYSPARM_PRODUCT_MODEL:="6BE1"
export ZLDSYSPARM_PRODUCT_MAC_QTY:=3
export ZLDSYSPARM_COMPATIBLE_PRODUCT_MODEL_NUM:=5
export ZLDSYSPARM_COMPATIBLE_PRODUCT_MODEL_0:="6BE1"
export ZLDSYSPARM_COMPATIBLE_PRODUCT_MODEL_1:="6FE1"
export ZLDSYSPARM_COMPATIBLE_PRODUCT_MODEL_2:="FFFF"
export ZLDSYSPARM_COMPATIBLE_PRODUCT_MODEL_3:="FFFF"
export ZLDSYSPARM_COMPATIBLE_PRODUCT_MODEL_4:="FFFF"
export ZLDSYSPARM_COMPATIBLE_PRODUCT_NAME_0:="NWA50AX"
export ZLDSYSPARM_COMPATIBLE_PRODUCT_NAME_1:="NWA55AXE"
export ZLDSYSPARM_COMPATIBLE_PRODUCT_NAME_2:=""
export ZLDSYSPARM_COMPATIBLE_PRODUCT_NAME_3:=""
export ZLDSYSPARM_COMPATIBLE_PRODUCT_NAME_4:=""
export ZLDSYSPARM_COMPATIBLE_PRODUCT_MAC_QTY_0:="03"
export ZLDSYSPARM_COMPATIBLE_PRODUCT_MAC_QTY_1:="03"
export ZLDSYSPARM_COMPATIBLE_PRODUCT_MAC_QTY_2:="00"
export ZLDSYSPARM_COMPATIBLE_PRODUCT_MAC_QTY_3:="00"
export ZLDSYSPARM_COMPATIBLE_PRODUCT_MAC_QTY_4:="00"
export ZLDSYSPARM_CPU_CORE_NUM:=4
export ZLDCONFIG_WTP_DUALIMAGE:=1
export ZLDSYSPARM_MAX_FW_SIZE:=(50 * 1024)
export ZLDSYSPARM_MAX_FW_FTP_QUOTA:=60000
export ZLDCONFIG_BUILD_SWITCH_ENABLE:=1
export ZLDCONFIG_BUILD_MINIPCI:=1
export ZLDCONFIG_ETH_STORM_CONTROL:=1
export ZLDSYSPARM_ETH_STORM_MIN_PPS_RATE:=64
export ZLDSYSPARM_ETH_STORM_RATE_SETTING_CAPS:=1
export ZLDSYSPARM_ETH_STORM_STORMING_GET_CAPS:=0
export ZLDSYSPARM_BOOTUP_ENABLED_PORT:=1
export ZLDCONFIG_BUILD_MINIPCI_NUM:=2
export ZLDSYSPARM_BUILD_PCMCIA_NUM:=0
export ZLDSYSPARM_BUILD_USB_NUM:=0
export ZLDSYSPARM_PCMCIA_SLOT1_TO_BUSNUM:=3
export ZLDSYSPARM_PCMCIA_SLOT2_TO_BUSNUM:=2
export ZLDSYSPARM_PCMCIA_SLOT_INTERFACE_OFFSET:=1
# ZLDCONFIG_BUILD_RTC is not set
export ZLDCONFIG_SUPPORT_NOR_STORAGE:=1
export ZLDSYSPARM_BOOT_DRIVE:="/dev/mtdblock"
export ZLD_FIXED_DISK_ID:=1
export ZLD_FIXED_DISK_VENDOR_ID:="ZyXEL "
export ZLD_FIXED_DISK_PRODUCT_ID:="ZyWALL_USG "
export ZLD_DISK_LOG_BLOCK_SIZE:=2048
export ZLDSYSPARM_DISK_LOG_BUF_SHIFT:=17
export ZLDSYSPARM_MAX_CONN_SESSION:=10000
export ZLDSYSPARM_BM_CODE_SIZE:=(192*(1<<10))
export ZLDCONFIG_GUI_REMOVE_EMAIL_REPORT_SUPPORT:=1
export ZLDSYSPARM_GUI_DIR:="/usr/local/zyxel-gui"
export ZLDSYSPARM_GUI_VER:=2
export ZLDSYSPARM_MAX_SOFTIRQ_RESTART:=2
export ZLDSYSPARM_NETDEV_BUDGET_READ_MOSTLY:=128
export ZLDSYSPARM_NTP_SYNC_PERIOD_HOUR:=6
export ZLDSYSPARM_MAX_STATIC_IPVVI_ADDRESS:=1
export ZLDSYSPARM_MAX_STATIC_IPVVI_ADDRESS_GATEWAY_LIST:=1
export ZLDSYSPARM_MAX_SLAAC_ADDRESS:=16
export ZLDSYSPARM_MAX_SLAAC_GW_ADDRESS:=16
export ZLDSYSPARM_MAX_DHCPVVI_ADDRESS:=16
export ZLDSYSPARM_MAX_IPVVI_RA_OPTIONS_PREFIX:=4
export ZLDSYSPARM_MAX_IPVVI_RA_OPTIONS_RDNS:=4
export ZLDSYSPARM_MAX_IPVVI_RA_OPTIONS_ROUTE:=4
export ZLDSYSPARM_MAX_DHCP6_LEASE_OBJECT_NUM:=1024
export ZLDSYSPARM_MAX_DHCP6_REQUEST_OBJECT_NUM:=1024
export ZLDSYSPARM_MAX_DHCP6_PD_ADDRESS_NUM:=1
export ZLDSYSPARM_MAX_DHCP6_PD_RA_NUM:=4
export AV_ZIP_MAX_SESSION:=50
export AV_RAR_LZSS_MAX_SESSION:=8
export AV_RAR_PPM_MAX_SESSION:=1
export AV_MAX_ZONE_TO_ZONE_RULE:=32
export AV_MAX_WHITE_LIST:=256
export AV_MAX_BLACK_LIST:=256
export AV_MAX_WBL_PATTERN_LENGTH:=80
export AV_MAX_STATISTICS:=500
export AV_MAX_STATISTICS_RANKING:=10
export AV_MAX_FULL_INSPECTION_CODE_SIZE:=24
export AV_MAX_INCR_INSPECTION_CODE_SIZE:=1
export ZLDSYSPARM_AV_FULL_ENGINE:=1
export ZLDSYSPARM_AV_INCR_ENGINE:=1
export ZLDSYSPARM_ADDRESS_OBJECT_MAX_NUM:=100
export ZLDSYSPARM_ADDRESS_GROUP_MAX_NUM:=25
export ZLDSYSPARM_OBJECT_GROUP_MEMBER_MAX:=64
export ZLDSYSPARM_SERVICE_OBJECT_MAX_NUM:=200
export ZLDSYSPARM_SERVICE_GROUP_MAX_NUM:=50
export ZLDSYSPARM_SERVICE_OBJECT_GROUP_MEMBER_MAX:=64
export ZLDSYSPARM_SCHEDULE_OBJECT_MAX_NUM:=16
export ZLDSYSPARM_SYSTEM_BUILTIN_ZONE_OBJECT_MAX_NUM:=7
export ZLDSYSPARM_USER_DEFINE_ZONE_OBJECT_MAX_NUM:=8
export ZLDSYSPARM_ZONE_OBJECT_MAX_NUM:=8
export ZLDSYSPARM_PHY_PORT_MAX_NUM:=1
export ZLDSYSPARM_ETH_IFACE_MAX_NUM:=1
export ZLDSYSPARM_VIR_IFACE_MAX_NUM:=4
export ZLDSYSPARM_VLAN_IFACE_MAX_NUM:=1
export ZLDSYSPARM_BRIDGE_IFACE_MAX_NUM:=1
export ZLDSYSPARM_USER_PPP_IFACE_MAX_NUM:=0
export ZLDSYSPARM_SYSTEM_PPP_IFACE_MAX_NUM:=0
export ZLDSYSPARM_SYSTEM_PPP_IFACE_START_NUM:=1
export ZLDSYSPARM_PPP_IFACE_MAX_NUM:=(1 + 0)
export ZLDSYSPARM_LAYER2VLAN_MAX_NUM:=4094
# ZLDCONFIG_AP_LAN_PROVISION is not set
# ZLDCONFIG_WLAN_BUILD_MADWIFI_DRIVER is not set
# ZLDCONFIG_WLAN_BUILD_ATHEROS_DRIVER is not set
export ZLDCONFIG_WLAN_BUILD_MTK_DRIVER:=1
export ZLDCONFIG_UBUS_SUPPORT:=1
# ZLDSYSPARM_WLAN_STATION_SUPPORT is not set
# ZLDSYSPARM_WLAN_WDS_SUPPORT is not set
export ZLDSYSPARM_WLAN_MAX_SLOT:=(0 + 2)
export ZLDSYSPARM_WLAN_MAX_AP:=8
export ZLDSYSPARM_WLAN_MAX_MAC_FILTER_ADDR:=128
export ZLDCONFIG_WLAN_11AC_SUPPORT:=1
export ZLDCONFIG_WLAN_11AX_SUPPORT:=1
export ZLDSYSPARM_WLAN_MAX_OWE:=3
export ZLDSYSPARM_MESH_MAX_AP:=5
export ZLDSYSPARM_WLAN_START_OWE:=(8 +5 +1)
export ZLDSYSPARM_WLAN_MAX_CLIENT:=512
export ZLDSYSPARM_WLAN_RADIO_PROFILE_SUPPORT:=64
export ZLDSYSPARM_WLAN_MONITOR_PROFILE_SUPPORT:=64
export ZLDSYSPARM_WLAN_SSID_PROFILE_SUPPORT:=64
export ZLDSYSPARM_WLAN_SECURITY_PROFILE_SUPPORT:=64
export ZLDSYSPARM_WLAN_MACFILTER_PROFILE_SUPPORT:=64
export ZLDSYSPARM_WLAN_MACFILTER_MAX_ENTRY:=512
export ZLDSYSPARM_WLAN_L2ISOLATION_PROFILE_SUPPORT:=16
export ZLDSYSPARM_WLAN_L2ISOLATION_MAX_ENTRY:=32
export ZLDSYSPARM_GUEST_SSID_PROFILE_SUPPORT:=16
export ZLDSYSPARM_GUEST_SSID_MAX_ENTRY:=32
export ZLDSYSPARM_WLAN_WDS_PROFILE_SUPPORT:=32
export ZLDSYSPARM_BRIDGE_MEMBER_MAX_NUM:=(1 + 1 +((0 + 2)*8))
export ZLDSYSPARM_DHCP_RELAY_NUM_PER_IFACE:=2
export ZLDSYSPARM_VIRTUAL_SERVER_MAX_NUM:=128
export ZLDSYSPARM_TRIGGER_PORT_PER_RULE:=8
export ZLDSYSPARM_POLICY_ROUTE_MAX_NUM:=100
export ZLDSYSPARM_USER_INTERFACE_TRUNK_MAX_NUM:=2
export ZLDSYSPARM_SYSTEM_INTERFACE_TRUNK_MAX_NUM:=1
export ZLDSYSPARM_INTERFACE_TRUNK_MAX_NUM:=(2 + 1)
export ZLDSYSPARM_STATIC_ROUTE_MAX_NUM:=64
export ZLDSYSPARM_FIREWALL_RULE_MAX_NUM:=500
export ZLDSYSPARM_SESSION_LIMIT_RULE_MAX_NUM:=500
export ZLDSYSPARM_IPSEC_VPN_MAX_CONN:=15
export ZLDSYSPARM_IPSEC_VPN_MAX_CONN_BASIC:=15
export ZLDSYSPARM_IPSEC_VPN_CONCENTRATOR_MAX_NUM:=2
export ZLDSYSPARM_IPSEC_VPN_QS_VER:=44
export ZLDSYSPARM_CON_USER_MAX_NUM:=1034
export ZLDSYSPARM_UAM_USER_NAME_LEN:=64
export ZLDSYSPARM_UAM_PASSWORD_LEN:=64
export ZLDSYSPARM_UAM_UNIQUE_LEN:=64
export ZLDSYSPARM_UAM_USER_ROLES_PER_EXT_GROUP_USER:=32
# SSL_HW_ACCELERATOR is not set
# ZLDCONFIG_SSLVPN_REVERSE_PROXY_SUPPORT is not set
# ZLDCONFIG_SSLVPN_FILE_SHARING_SUPPORT is not set
export ZLDSYSPARM_SSL_VPN_DEFAULT_ACTIVE_USERS:=1
export ZLDSYSPARM_SSL_VPN_MAX_ACTIVE_USERS:=5
export ZLDSYSPARM_SSL_VPN_MAX_SESSIONS:=15
export ZLDSYSPARM_SSL_VPN_USER_NAME_LEN:=(64)
export ZLDSYSPARM_SSL_VPN_MAX_POLICY:=16
export ZLDSYSPARM_SSL_VPN_MAX_POLICY_APPLICATION:=8
export ZLDSYSPARM_SSL_VPN_MAX_POLICY_NETWORK:=4
export ZLDSYSPARM_SSL_VPN_MAX_POLICY_USER:=16
export ZLDSYSPARM_SSL_VPN_MAX_APP:=64
export ZLDSYSPARM_SSL_VPN_MAX_OWA_APP:=1
export ZLDSYSPARM_SSL_VPN_MAX_THREAD_NUMBER:=3
export ZLDSYSPARM_SSL_VPN_MIN_THREAD_NUMBER:=1
# ZLDCONFIG_NAC is not set
export ZLDSYSPARM_NAC_MAX_POLICY:=1024
export ZLDSYSPARM_CERT_STORAGE_SIZE_LIMIT:=64000
export ZLDSYSPARM_CERT_NAME_LEN:=32
export ZLDSYSPARM_BUILDIN_CACERT_PATH:="/etc/zyxel/cert/cacert.buildin.pem"
export ZLDSYSPARM_CACERT_PATH:="/etc/zyxel/pikachu/cacert.pem"
export ZLDSYSPARM_APP_PATROL_ALLOW_PORT_MAX:=8
export ZLDSYSPARM_APP_PATROL_MAX_ADDR_POOL:=5000
export ZLDSYSPARM_APP_PATROL_DEFAULT_PORT_MAX:=8
export ZLDSYSPARM_APP_PATROL_MAX_EXCEP_RULE:=24
export ZLDSYSPARM_APP_PATROL_MAX_OTHER_RULE:=24
export ZLDSYSPARM_APP_PATROL_MAX_PROTO_NUM:=32
export SYSTEM_DEFAULT_PACKET_CHECK:=8
export ZLDSYSPARM_AAA_LDAP_GROUP_MAX_NUM:=2
export ZLDSYSPARM_AAA_LDAP_SERVER_MAX_NUM:=2
export ZLDSYSPARM_AAA_RADIUS_GROUP_MAX_NUM:=2
export ZLDSYSPARM_AAA_RADIUS_SERVER_MAX_NUM:=2
export ZLDSYSPARM_AAA_AD_GROUP_MAX_NUM:=4
export ZLDSYSPARM_AAA_AD_SERVER_MAX_NUM:=2
export ZLDSYSPARM_AAA_AUTH_METHOD_MAX_NUM:=4
export ZLDSYSPARM_AAA_DEF_ACCT_INTERIM_INT:=600
export ZLDSYSPARM_AAA_DEF_ACCT_INTERIM_STR:="600"
export ZLDSYSPARM_AAA_DEF_ACCT_INTERIM_MINUTE_STR:="10"
export ZLDSYSPARM_AUTH_SERVER_TRUSTED_CLIENT_MAX_NUM:=32
export ZLDSYSPARM_LOCAL_USER_MAX_NUM:=64
export ZLDSYSPARM_ADMIN_USER_MAX_NUM:=5
export ZLDSYSPARM_USER_GROUP_MAX_NUM:=16
export ZLDSYSPARM_DNS_ADDR_RECORD_MAX_NUM:=32
export ZLDSYSPARM_DNS_DOMAIN_ZONE_FORWARD_MAX_NUM:=4
export ZLDSYSPARM_DNS_MX_RECORD_MAX_NUM:=4
export ZLDSYSPARM_HTTP_PROCESS_MAX_NUM:=62
export APACHE:=1
export LIGHTTPD:=2
export ZLDSYSPARM_HTTP_WEB_SERVER_PACKAGE:=2
export ZLDSYSPARM_SNMP_INTERFACE_CACHE_TIMEOUT:=300
export ZLDSYSPARM_ACCESS_CONTROL_RULE_MAX_NUM:=8
export ZLDSYSPARM_DDNS_PROFILE_MAX_NUM:=5
export ZLDSYSPARM_DHCP_NETWORK_POOL_MAX_NUM:=1 +1 +1
export ZLDSYSPARM_DHCP_HOST_POOL_MAX_NUM:=64
export ZLDSYSPARM_SSL_DEFAULT_CIPHER_SUITE:="aes des 3des"
export ZLDSYSPARM_SNMP_V3USER_MAX_NUM:=8
export ZLDSYSPARM_SNMP_V3USER_PASSWD_MIN_LENGTH:=8
export ZLDSYSPARM_EVENT_LOG_ENTRY_MAX_NUM:=512
export ZLDSYSPARM_DEBUG_LOG_ENTRY_MAX_NUM:=1
export ZLDSYSPARM_LOG_EMAIL_SERVER_SUPPORT:=2
export ZLDSYSPARM_LOG_SYSLOG_SERVER_SUPPORT:=4
export ZLDSYSPARM_TRAFFIC_REPORT_MAX_ENTRY:=20
export ZLDSYSPARM_OSPF_AREA_MAX_NUM:=16
export ZLDSYSPARM_ILB_DNS_SVC_MAX_NUM:=32
export ZLDSYSPARM_ILB_DNS_DEST_MAX_NUM:=8
export ZLDCONFIG_WATCHDOG_SUPPORT:=1
export ZLDCONFIG_LAST_BOOT_REASON_SUPPORT:=1
export ZLDCONFIG_APP_AUTO_RECOVER:=1
export ODM_CONFIG_ACTIVATE:=0
export ODM_SYSPARM_COMPANY_NAME:=""
export ODM_SYSPARM_COMPANY_WEBSITE:=""
export ODM_SYSPARM_PRODUCT_NAME:=""
export ODM_SYSPARM_PRODUCT_NAME1:=""
export ODM_SYSPARM_PRODUCT_SERIES_NAME:="Device"
export ODM_SYSPARM_PRODUCT_ZONE_NAME:="Device"
export ODM_SYSPARM_REGIST_SERVER_WEBSITE:=""
export ODM_SYSPARM_REGIST_UPDATE_SERVER_WEBSITE:=""
export ZLDSYSPARM_CAPWAP_DTLS_SOCKET:=1
export ZLDSYSPARM_CAPWAP_DTLS_SECURITY:=1
export ZLDSYSPARM_CAPWAP_AC_PREFER_MAX_NUM:=2
export ZLDSYSPARM_CAPWAP_WTP_MAX_NUM:=24
export ZLDSYSPARM_CAPWAP_WAIT_WTP_MAX_NUM:=(24 * 2)
export ZLDSYSPARM_CAPWAP_TASKEVT_WM:=100
export ZLDSYSPARM_CAPWAP_AC_SUPPORT_MODEL_NAME_LIST:="(NWA3160-N|NWA3550-N|NWA3560-N)"
export ZLDSYSPARM_CAPWAP_AC_SUPPORT_MODEL_NAME_HELP:="<NWA3160-N,NWA3550-N,NWA3560-N>"
export ZLDCONFIG_WLAN_ROGUEAP_DETECTION_SUPPORT:=1
export ZLDCONFIG_WLAN_ROGUEAP_CONTAINMENT_SUPPORT:=1
export ZLDSYSPARM_WLAN_ROGUEAP_DETECTED_DEVICE_NUM:=512
export ZLDSYSPARM_WLAN_ROGUE_AP_NUM:=64
export ZLDSYSPARM_WLAN_FRIENDLY_AP_NUM:=64
export ZLDSYSPARM_WLAN_CONTAINED_MAC_NUM:=256
export ZLDSYSPARM_WLAN_ROGUE_RULE_SSID_KEYWORD_NUM:=10
export ZLDSYSPARM_WLAN_FRAME_CAPTURE_MAX_SOURCE_NUM:=240
export ZLDCONFIG_FILEMANAGE_SUPPORT:=1
export ZLDCONFIG_SUPPORT_SHOW_SYS_FILE:=1
export ZLDCONFIG_WTP_SUPPORT_SNMP_PROVISION:=1
export ZLDSYSPARM_LLDP_RCD_WAIT:=23
export ZLDSYSPARM_LLDP_RCD_RETRANSMIT:=20
export ZLDSYSPARM_LLDP_TX_INTERVAL:=30
export ZLDSYSPARM_LLDP_TX_HOLD:=4
export ZLDSYSPARM_LLDP_TOLERANCE_TIME:=16
export ZLDCONFIG_WTP_SAVE_CONFIG:=1
export ZLDCONFIG_MEMCHECK_SUPPORT:=1
export ZLDSYSPARM_WLAN_SIC_INTERVAL:=1
export ZLDSYSPARM_WLAN_SIC_NUMBER:=1
export ZLDSYSPARM_WLAN_SIC_TYPE:=1
export ZLDCONFIG_ROAMING_LOG_SUPPORT:=1
export ZLDSYSPARM_ROAMING_GROUP_LEN:=15
export ZLDCONFIG_CLOUD_MODE_SUPPORT:=1
export ZLDSYSPARM_CERT_DEV:="/etc/zyxel/pikachu/nebula.cert"
export ZLDSYSPARM_ETC_WRITABLE_ZYXEL_CFG_DIR:="/etc/zyxel/ftp/nebula"
export ZLDSYSPARM_NEBULA_NC_RUNNING_CFG_BACKUP_DIR:="/etc/zyxel/ftp/netopeer"
export ZLDSYSPARM_NEBULA_NC_RUNNING_CFG_DIR:="/var/netopeer/netopeer"
export FORIEGN_AUTHENTICATED_STA_PATH:="/tmp/sta_lists/foreign-auth-sta.txt"
export ZLDCONFIG_NEBULA_NTP_UPDATE_RETRY:=1
export ZLDCONFIG_NEBULA_NTP_PROTECT:=1
export ZLDCONFIG_ZYLOG_DROPPED_COUNT:=1
export ZLDCONFIG_DHCP_SNIFFER_SUPPORT:=1
export ZLDCONFIG_ZYLOG_MAX_MESSAGE_LEN:=512
export ZLDCONFIG_SEND_USER_INFO_TO_NCC:=1
export ZLDCONFIG_NEBULA_REMOTE_SUPPORT:=1
# ZLDCONFIG_AAA_IPV6_SUPPORT is not set
export AAA_WEB_PORTAL:=1
export AAA_8021X_CLOUD_AUTHENTICATION:=1
export ZLDSYSPARM_AAA_WEB_PORTAL_SLOT_BASE_OFFSET:=10000
export ZLDSYSPARM_AAA_WEB_PORTAL_HTTP_OFFSET:=80
export ZLDSYSPARM_AAA_WEB_PORTAL_HTTPS_OFFSET:=443
export ZLDSYSPARM_AAA_WEB_PORTAL_MARK_NUMBER:=4100
export ZLDSYSPARM_AAA_WEB_PORTAL_MARK_SLOT_INDEX_OFFSET:=50
export WHITELIST_STA_PATH_SLOT1:="/tmp/sta_lists/whitelist-sta-slot1.txt"
export WHITELIST_STA_PATH_SLOT2:="/tmp/sta_lists/whitelist-sta-slot2.txt"
export ZLDCONFIG_AAA_WALLED_GARDEN_SUPPORT:=1
export ZLDSYSPARM_WALLED_GARDEN_PROFILE_SUPPORT:=16
export ZLDSYSPARM_WALLED_GARDEN_MAX_ENTRY:=32
export ZLDCONFIG_SOCIAL_LOGIN_SUPPORT:=1
export ZLDCONFIG_NEBULA_PORTAL_ACCOUNTING_SUPPORT:=1
export ZLDCONFIG_WEB_PORTAL_LIMIT_SUPPORT:=1
export ZLDCONFIG_FB_WIFI:=1
export ZLDCONFIG_ORIGINAL_URL:=1
export ZLDCONFIG_MULTI_FACTOR_AUTHENTICATION_SUPPORT:=1
# ZLDCONFIG_FINDME_URL is not set
export ZLDCONFIG_FINDME_URL_MARK_NUMBER:=4200
export ZLDCONFIG_LOGOUT_IP_MARK_NUMBER:=4400
export ZLDSYSPARM_WLAN_CAPTIVE_PROFILE_SUPPORT:=64
export ZLDSYSPARM_WLAN_WHITELIST_PROFILE_SUPPORT:=64
export ZLDSYSPARM_WLAN_CAPTIVE_PARAMETER_PROFILE_SUPPORT:=32
export ZLDSYSPARM_WLAN_WHITELIST_MAX_ENTRY:=256
export ZLDCONFIG_AP_FACTORY_DEFAULT_SUPPORT:=1
export ZLDCONFIG_UTF8_SSID_SUPPORT:=1
export ZLDCONFIG_SSID_NAT_SUPPORT:=1
export ZLDCONFIG_LINUX_PAM_MODIFICATION:=1
# ZLDCONFIG_THIRD_RADIO_SUPPORT is not set
# ZLDCONFIG_ZERO_WAIT_DFS_SUPPORT is not set
export ZLDCONFIG_AP_LOAD_BALANCING_GROUP_SUPPORT:=1
export LOADBALANCING_GROUP_NUM:=2
export LOADBALANCING_GROUP_LEN:=32
# ZLDCONFIG_INIT_OPENRC is not set
export ZLDSYSPARM_WLAN_AAA_MAX_VAP:=(8 +5 +3)
# ZLDCONFIG_ENCRYPTED_WPA_PSK is not set
export ZLDCONFIG_WAR_NCC_MISCONFIGURED:=1
export DISABLE_WAR_NCC_MISCONFIGURED:="/tmp/disable_war_ncc_misconfigured"
export ZLDCONFIG_GUI_BASIC_FEATURE_SUPPORT:=1
export ZLDCONFIG_PACKET_CAPTURE_SUPPORT:=1
# ZLDCONFIG_PCAP_MONITOR is not set
# ZLDCONFIG_PCAP_MONITOR_WTP is not set
export ZLDCONFIG_REMOTE_CAPTURE_SUPPORT:=1
# ZLDCONFIG_WIRELESS_CAPTURE_SUPPORT is not set
export ZLDCONFIG_MD5_SUPPORT:=1
export ZLDCONFIG_NEBULA_AP_SUPPORT:=1
export ZLDCONFIG_IPERF_SUPPORT:=1
